# Generated by Django 4.2.5 on 2023-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingstatus',
            name='date_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
